name: vidipress_core
description: A standalone Flutter/Dart package for video compression
version: 1.0.0
repository: https://github.com/nathfavour/vidipress_core.git

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
